CREATE TABLE `member` (
    `member_id` INT(11) NOT NULL COMMENT '会员ID（主键）',
    `phone` VARCHAR(16) NOT NULL COMMENT '手机号（唯一索引）',
    `status` INT(3) NOT NULL DEFAULT '1' COMMENT '状态（索引）: 0失效，1正常,  4 黑名单(禁止任何操作)',
    `updated_at` INT(10) NOT NULL COMMENT '更新时间',
    `created_at` INT(10) NOT NULL COMMENT '创建时间',
    PRIMARY KEY (`member_id`),
    INDEX `status_idx` (`status`),
    INDEX `member_phone_idx` (`phone`) USING BTREE
) COMMENT='会员基础信息表' COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE `member_profile` (
    `member_id` INT(11) NOT NULL,
    `nickname` VARCHAR(45) NOT NULL COMMENT '用户昵称',
    `headimgurl` TEXT NULL COMMENT '头像地址',
    `gender` INT(3) NOT NULL DEFAULT '0' COMMENT '性别，1男，2女，0保密',
    `birthday` INT(11) NOT NULL COMMENT '生日',
    `updated_at` INT(11) NOT NULL COMMENT '更新时间',
    `created_at` INT(11) NOT NULL COMMENT '创建时间',
    PRIMARY KEY (`member_id`),
) COMMENT='会员资料表' COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE `member_address` (
    `member_address_id` INT(11) NOT NULL COMMENT '收件地址ID',
    `member_id` INT(11) NOT NULL COMMENT '顾客ID',
    `name` VARCHAR(500) NOT NULL COMMENT '收件人姓名',
    `phone` VARCHAR(500) NOT NULL COMMENT '收件人联系电话',
    `province` VARCHAR(45) NOT NULL COMMENT '省份',
    `province_code` VARCHAR(16) NOT NULL COMMENT '省份编号',
    `city` VARCHAR(45) NOT NULL COMMENT '城市',
    `city_code` VARCHAR(16) NOT NULL COMMENT '城市编码',
    `area` VARCHAR(45) NOT NULL COMMENT '区/县',
    `area_code` VARCHAR(32) NOT NULL COMMENT '区/县编码',
    `street` VARCHAR(128) NULL DEFAULT NULL COMMENT '街道/社区名称（天虹到家使用）',
    `street_code` VARCHAR(165) NULL DEFAULT NULL COMMENT '街道/社区编码（天虹到家使用）百度',
    `detail` VARCHAR(1000) NULL DEFAULT NULL COMMENT '详细地址信息',
    `zip_code` VARCHAR(10) NULL DEFAULT NULL COMMENT '邮政编码',
    `is_default` INT(3) NOT NULL DEFAULT '1' COMMENT 'is_default = 1  非默认地址   is_default = 2 默认地址',
    `deleted` INT(3) NOT NULL DEFAULT '1' COMMENT 'deleted    = 1  未删除       deleted    = 2 已删除',
    `updated_at` INT(10) NOT NULL DEFAULT '0' COMMENT '更新时间',
    `created_at` INT(10) NOT NULL DEFAULT '0' COMMENT '创建时间',
    `gender` INT(5) NULL DEFAULT '0' COMMENT '性别，1男，2女，0保密',
    `salt` VARCHAR(26) NULL DEFAULT NULL COMMENT '盐',
    PRIMARY KEY (`member_address_id`),
    INDEX `member_id_idx` (`member_id`)
) COMMENT='会员收件地址表' COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE `member_thirdparty` (
    `member_thirdparty_id` INT(11) NOT NULL COMMENT '第三方平台自增ID',
    `member_id` INT(11) NOT NULL DEFAULT '195' COMMENT '会员ID',
    `platform` INT(3) NOT NULL COMMENT '数据来源平台（索引）: 1 APP, 2 QQ, 3 微博, 4,微信,5 微信公众号,6 APP快捷登录, 7 PC快捷登录, 8 PC ,9小程序,11:apple ID',
    `openid` VARCHAR(100) NOT NULL COMMENT '第三方openid',
    `unionid` VARCHAR(100) NULL DEFAULT NULL COMMENT '微信unionid',
    `updated_at` INT(10) NOT NULL COMMENT '更新时间',
    `created_at` INT(10) NOT NULL COMMENT '创建时间',
    PRIMARY KEY (`member_thirdparty_id`),
    INDEX `member_id_idx` (`member_id`) USING BTREE,
    INDEX `unionid_Index` (`unionid`)
) COMMENT='第三方平台信息表' COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE `order_sale` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_no` VARCHAR(32) NOT NULL COMMENT '订单号',
    `channel` TINYINT(2) NOT NULL COMMENT '订单渠道： 2=APP，3=PC ，4=WAP，5=小程序，6=微信',
    `order_type` TINYINT(2) NOT NULL COMMENT '订单类型：1=普通订单，3=虚拟订单，4=积分订单',
    `pay_status` TINYINT(2) NOT NULL DEFAULT '0' COMMENT '支付状态 1-待支付 3-未支付取消 4-已支付 5-支付取消',
    `order_status` SMALLINT(4) NOT NULL COMMENT '订单状态  1-处理中，2-创建中，3-待支付，4=未支付取消，5-自动审核中，6-人工审核中，7=审核取消，8-待发货，9=未出库取消，10-拒收中，11-已发货,12-已拒收，13-已完成',
    `freight` DECIMAL(10,5) NOT NULL DEFAULT '0.00000' COMMENT '运费',
    `total_product_price` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品折前总金额',
    `total_pay_amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '实付',
    `real_pay_amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '实收',
    `total_discount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠',
    `total_give_integral` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '赠送总积分',
    `weight` DECIMAL(15,5) NULL DEFAULT '0.00000' COMMENT '订单商品重量',
    `consignee` VARCHAR(128) NULL DEFAULT NULL COMMENT '收货人姓名',
    `phone` VARCHAR(32) NULL DEFAULT NULL COMMENT '收货人手机号码',
    `county_code` VARCHAR(32) NULL DEFAULT NULL COMMENT '收货人区域编码',
    `address_detail` VARCHAR(255) NULL DEFAULT NULL COMMENT '收货人具体地址',
    `order_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下单时间',
    `member_id` INT(11) NULL DEFAULT '0' COMMENT '会员id',
    `customer_remark` VARCHAR(500) NULL DEFAULT NULL COMMENT '顾客备注',
    `service_remark` VARCHAR(1024) NULL DEFAULT NULL COMMENT '客服备注',
    `finish_time` TIMESTAMP NULL DEFAULT NULL COMMENT '完成时间',
    `pay_time` TIMESTAMP NULL DEFAULT NULL COMMENT '支付时间',
    `confirm_time` TIMESTAMP NULL DEFAULT NULL COMMENT '审核时间',
    `deleted` TINYINT(2) NOT NULL DEFAULT '0' COMMENT '前端是否不展示（顾客删除） 1=不展示 0=展示',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    PRIMARY KEY (`id`),
    INDEX `idx_order_no` (`order_no`),
    INDEX `idx_finish_time` (`finish_time`),
    INDEX `idx_member_id` (`member_id`) USING BTREE,
    INDEX `idx_order_status` (`order_status`)
) COMMENT='正向订单主表' COLLATE='utf8mb4_general_ci' ENGINE=InnoDB ;


CREATE TABLE `order_sale_item` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_no` VARCHAR(32) NOT NULL COMMENT '订单号',
    `order_item_no` VARCHAR(34) NOT NULL COMMENT '订单商品明细行号',
    `sale_qty` INT(11) NOT NULL COMMENT '销售数量',
    `sale_price` DECIMAL(10,2) NOT NULL COMMENT '（单）销售单价:折前价',
    `item_discount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '（总）商品折扣',
    `item_pay_discount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '（总）支付优惠',
    `item_pay_amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '（总）订单行应付金额:折后总金额',
    `market_price` DECIMAL(11,2) NULL DEFAULT NULL COMMENT '（单）市场价',
    `item_give_integral` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '（总）商品赠送积分',
    `weight` DECIMAL(15,5) NULL DEFAULT NULL COMMENT '（总）商品重量',
    `sale_unit` VARCHAR(32) NULL DEFAULT NULL COMMENT '销售单位',
    `product_id` INT(11) NULL DEFAULT NULL COMMENT '商品id',
    `product_code` VARCHAR(40) NULL DEFAULT NULL COMMENT '商品编码',
    `product_name` VARCHAR(256) NULL DEFAULT NULL COMMENT '商品名称',
    `product_property` VARCHAR(256) NULL DEFAULT NULL COMMENT '商品附加信息（如色码款）',
    `product_image_url` VARCHAR(1024) NULL DEFAULT NULL COMMENT '商品主图url',
    `sku_id` INT(11) NULL DEFAULT NULL COMMENT 'sku ID',
    `sku_code` VARCHAR(64) NULL DEFAULT NULL COMMENT 'SKU编码(物料编号)',
    `item_type` TINYINT(2) NULL DEFAULT NULL COMMENT '订单行类别：1=实体商品(普通商品)，2=赠品，3=组合商品，4=积分商品，5=虚拟商品',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    PRIMARY KEY (`id`),
    INDEX `idx_order_no` (`order_no`),
    INDEX `idx_order_item_no` (`order_item_no`),
    INDEX `idx_updated_at` (`updated_at`)
) COMMENT='正向订单商品明细表' COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE `order_pay` (
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_no` VARCHAR(32) NOT NULL COMMENT '订单号（索引）' COLLATE 'utf8_general_ci',
    `pay_code` VARCHAR(50) NOT NULL COMMENT '支付方式编码（索引）' COLLATE 'utf8_general_ci',
    `pay_name` VARCHAR(32) NOT NULL COMMENT '支付方式名称' COLLATE 'utf8_general_ci',
    `pay_amount` DECIMAL(10,2) NOT NULL COMMENT '支付金额(人民币)',
    `serial_no` VARCHAR(64) NULL DEFAULT NULL COMMENT '交易流水号（银行、微信、支付宝）' COLLATE 'utf8_general_ci',
    `pay_no` VARCHAR(32) NULL DEFAULT NULL COMMENT '支付号' COLLATE 'utf8_general_ci',
    `pay_time` TIMESTAMP(6) NULL DEFAULT NULL COMMENT '顾客实际支付时间',
    `status` TINYINT(2) NOT NULL DEFAULT '0' COMMENT '状态  0：待支付，1：已支付',
    `pay_account` VARCHAR(32) NULL DEFAULT NULL COMMENT '支付账号',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    PRIMARY KEY (`id`),
    INDEX `idx_order_no` (`order_no`),
    INDEX `idx_pay_code` (`pay_code`),
    INDEX `idx_updated_at` (`updated_at`)
) COMMENT='订单支付信息表' COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

CREATE TABLE `order_promotion` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_no` varchar(20) NOT NULL COMMENT '订单号（索引）',
  `order_item_no` varchar(24) DEFAULT NULL COMMENT '订单商品行号（索引）',
  `promo_type` tinyint(4) DEFAULT NULL COMMENT '促销类型   1=单品直减，2=单品赠品，3=订单满减，4=订单赠品',
  `promo_id` int(11) DEFAULT NULL COMMENT '促销id',
  `promo_code` varchar(32) DEFAULT NULL COMMENT '促销编码',
  `promo_name` varchar(255) DEFAULT NULL COMMENT '促销规则名称',
  `promo_amount` decimal(10,2) DEFAULT NULL COMMENT '促销优惠金额',
  `promo_qty` int(11) DEFAULT NULL COMMENT '商品数量',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_order_item_no` (`order_item_no`),
  KEY `idx_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单促销信息';

CREATE TABLE `order_extension` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_no` varchar(32) DEFAULT NULL COMMENT '订单号（索引）',
  `cancel_reason_no` varchar(10) CHARACTER SET utf8 DEFAULT NULL COMMENT '取消订单原因编号  101=商品价格，102=未获得优惠优惠券，103=支付遇到问题，104=更换支付方式，105=错误或重复下单，106=更换/添加新商品，107=更换配送地址,108=不在配送范围,109=其他原因,110=运费问题,111=配送时间',
  `is_blacklist` tinyint(2) DEFAULT '0' COMMENT '是否黑名单 0，否    1，是',
  `is_priviledged` tinyint(2) DEFAULT '0' COMMENT '是否大客户 0:否,1:（大客户）',
  `warn_info` varchar(512) CHARACTER SET utf8 DEFAULT NULL COMMENT '订单预警/炒货信息',
  `ip` varchar(256) CHARACTER SET utf8 DEFAULT NULL COMMENT '下单IP地址',
  `version` varchar(45) CHARACTER SET utf8 DEFAULT NULL COMMENT 'app版本号',
  `device_type` varchar(45) CHARACTER SET utf8 DEFAULT NULL COMMENT '设备类型',
  `screen_name` varchar(32) DEFAULT NULL COMMENT '页面名称',
  `key_word` varchar(32) DEFAULT NULL COMMENT '搜索关键词',
  `screen_tn` varchar(32) DEFAULT NULL COMMENT '页面追踪tn号',
  `min_delivery_days` int(11) DEFAULT NULL COMMENT '发货时间：最小时间（天数）',
  `max_delivery_days` int(11) DEFAULT NULL COMMENT '发货时间：最大时间（天数）',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_updated_at` (`updated_at`),
  KEY `idx_order_no` (`order_no`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='销售订单扩展信息表';

CREATE TABLE `order_item_extension` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_no` varchar(32) NOT NULL COMMENT '订单号（索引）',
  `order_item_no` varchar(34) NOT NULL COMMENT '订单商品明细行号（索引）',
  `cost_price` decimal(10,2) DEFAULT NULL COMMENT '（单）库存成本价',
  `barcode` varchar(64) DEFAULT NULL COMMENT '条形码，国标码',
  `supplier_code` varchar(10) DEFAULT NULL COMMENT '供应商编码',
  `rebate_amount` decimal(10,2) DEFAULT NULL COMMENT '明细行返利金额',
  `rebate_member_id` int(11) DEFAULT NULL COMMENT '返利会员id',
  `rebate_type` tinyint(2) DEFAULT NULL COMMENT '返利金额类型 1=固定金额返利,2=百分比返利',
  `room_id` int(11) DEFAULT NULL COMMENT '直播间id',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_order_item_no` (`order_item_no`),
  KEY `idx_supplier_code` (`supplier_code`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单商品明细扩展表';


CREATE TABLE `product` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '商品ID，主键',
  `code` varchar(40) NOT NULL COMMENT '商品编码',
  `name` varchar(256) NOT NULL,
  `supplier_id` int(11) DEFAULT NULL COMMENT '所属供应商id',
  `category_id` int(11) DEFAULT NULL COMMENT '运营分类ID',
  `brand_id` int(4) DEFAULT NULL COMMENT '品牌id',
  `product_type` tinyint(2) NOT NULL DEFAULT '1' COMMENT '产品类型 ：1=实体商品；   2=虚拟商品',
  `weight` decimal(20,5) NOT NULL DEFAULT '0.00000' COMMENT '重量，用于计算运费',
  `weight_uom` tinyint(2) DEFAULT '1' COMMENT '重量单位,1=千克 2=克 3=毫克 4=吨',
  `length` decimal(20,5) DEFAULT NULL COMMENT '长,单位米',
  `width` decimal(15,5) DEFAULT NULL COMMENT '宽,单位米',
  `height` decimal(20,5) DEFAULT NULL COMMENT '高,单位米',
  `volume` decimal(20,5) DEFAULT NULL COMMENT '体积',
  `is_integral` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否积分商品： 0为否，1为是',
  `is_gift` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否可为赠品： 0为否，1为是, 2.可赠可售',
  `expiration` decimal(20,0) DEFAULT NULL COMMENT '保质期',
  `madein` varchar(128) DEFAULT NULL COMMENT '产地',
  `buy_max` int(10) DEFAULT NULL COMMENT '最大购买数',
  `buy_min` int(10) DEFAULT NULL COMMENT '最小购买数',
  `deleted` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否删除 1=已删除 0=未删除',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_prd_categoryid` (`category_id`) USING BTREE,
  KEY `idx_prd_merchantid` (`merchant_id`) USING BTREE,
  KEY `idx_prd_brandid` (`brand_id`),
  KEY `idx_prd_supplierid` (`supplier_id`),
  KEY `idx_prd_productcode` (`code`) USING BTREE,
  KEY `idx_updated_at` (`updated_at`) USING BTREE,
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='商品基础信息表';

CREATE TABLE `product_attribute` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL COMMENT '商品ID',
  `attr_id` int(11) NOT NULL COMMENT '属性id',
  `value` varchar(64) DEFAULT NULL COMMENT '文本值，保存属性为文本的value值',
  `deleted` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否删除 1=已删除 0=未删除',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间,根据当前时间戳更新',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_product_id` (`product_id`) USING BTREE,
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='商品属性表';

CREATE TABLE `product_image` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '商品ID',
  `product_id` int(11) NOT NULL COMMENT '商品ID',
  `title` varchar(256) DEFAULT NULL COMMENT '图片标题',
  `img_source` varchar(1024) DEFAULT NULL COMMENT ' 原图片',
  `img_large` varchar(1024) DEFAULT NULL COMMENT '手机端列表图片规格 600*600',
  `img_medium` varchar(1024) DEFAULT NULL COMMENT '中图，390*390',
  `sort` int(11) DEFAULT NULL COMMENT '排序，升序，越小越靠前',
  `description` varchar(1024) DEFAULT NULL COMMENT '图片描述',
  `deleted` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否删除 1=已删除 0=未删除',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间,根据当前时间戳更新',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_product_id` (`product_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='商品图片表';

CREATE TABLE `product_text` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL COMMENT '商品ID',
  `name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品名称',
  `short_title` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '短描述',
  `short_description` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '短描述',
  `web_description` longtext COLLATE utf8mb4_unicode_ci COMMENT 'web商品描述详情',
  `mobile_description` longtext COLLATE utf8mb4_unicode_ci COMMENT '手机商品描述详情',
  `aftersales_service_description` mediumtext COLLATE utf8mb4_unicode_ci COMMENT '售后服务描述',
  `merchant_id` bigint(20) NOT NULL COMMENT '商家ID',
  `search_keywords` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '搜索关键字，用于前台搜索引擎',
  `seo_title` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'seo页面标题',
  `seo_keywords` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'seo页面关键字',
  `deleted` tinyint(2) DEFAULT '0' COMMENT '是否删除 1=已删除 0=未删除',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间,根据当前时间戳更新',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_product_id_merchant_id_deleted` (`product_id`,`merchant_id`,`deleted`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品名称、描述等信息';

CREATE TABLE `sku` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '色码款ID，主键',
  `product_id` int(11) NOT NULL COMMENT '商品ID，索引',
  `code` varchar(40) DEFAULT NULL COMMENT 'sku唯一编码',
  `barcode` varchar(32) DEFAULT NULL COMMENT '商品条形码，索引',
  `item_num` varchar(16) DEFAULT NULL COMMENT '外部商品编号',
  `name` varchar(150) DEFAULT NULL COMMENT 'sku名称',
  `sort` int(11) DEFAULT '999' COMMENT '排序升序，值越小越靠前',
  `deleted` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否删除 1=已删除 0=未删除',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间,根据当前时间戳更新',
  PRIMARY KEY (`id`),
  KEY `idx_sku_product_id` (`product_id`) USING BTREE,
  KEY `idx_sku_item_num` (`item_num`) USING BTREE,
  KEY `idx_sku_code` (`code`),
  KEY `idx_sku_barcode` (`barcode`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='商品色码款表';

CREATE TABLE `sku_image` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sku_id` int(11) NOT NULL,
  `image_id` int(11) NOT NULL COMMENT 'sku图片，商品图片Id,来源product_image主键',
  `product_id` int(11) NOT NULL COMMENT '商品ID',
  `is_primary_image` tinyint(2) DEFAULT '0' COMMENT '是否主图 1=是 0=否',
  `sort` int(11) NOT NULL DEFAULT '999' COMMENT '排序，升序，越小越靠前',
  `deleted` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否删除 1=已删除 0=未删除',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间,根据当前时间戳更新',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_skuimg_sid` (`sku_id`) USING BTREE,
  KEY `idx_skuimg_pid` (`product_id`),
  KEY `idx_skuimg_imgid` (`image_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='色码款图片';

CREATE TABLE `sku_price` (
  `id` bigint(14) NOT NULL AUTO_INCREMENT,
  `sku_id` int(11) NOT NULL COMMENT 'SKU ID',
  `product_id` int(11) NOT NULL COMMENT '商品id',
  `channel` tinyint(2) NOT NULL COMMENT '渠道 1=app 2=pc 3=web 4=手机web 5=微信',
  `merchant_id` bigint(20) NOT NULL COMMENT '商家id',
  `currency` tinyint(2) NOT NULL COMMENT '货币类型  （1，RENMINBI：人民币 ；2，INTEGRAL 积分）',
  `sale_price` decimal(20,2) NOT NULL COMMENT '销售价',
  `market_price` decimal(20,2) DEFAULT NULL COMMENT '市场价',
  `cost_price` decimal(20,2) DEFAULT NULL COMMENT '成本价',
  `deleted` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否删除 1=已删除 0=未删除',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间,根据当前时间戳更新',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_price_pid` (`product_id`) USING BTREE,
  KEY `idx_updated_at` (`updated_at`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='价格表';

CREATE TABLE `sku_stock` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `sku_id` int(11) NOT NULL COMMENT '商品sku id',
  `product_id` int(11) NOT NULL COMMENT '商品id',
  `channel` tinyint(2) NOT NULL COMMENT '渠道 1=app 2=pc 3=web 4=手机web 5=微信 ',
  `merchant_id` bigint(20) DEFAULT NULL COMMENT '商家id',
  `warehouse_id` int(11) DEFAULT NULL COMMENT '仓库id',
  `stock_type` tinyint(2) DEFAULT NULL COMMENT '1.普通商品库存  2.积分商品库存 ',
  `total_stock` int(11) DEFAULT NULL COMMENT 'sku总库存',
  `stock` int(11) DEFAULT '0' COMMENT 'SKU可售库存',
  `order_stock` int(11) DEFAULT NULL COMMENT '订单冻结库存',
  `safety_stock` int(11) DEFAULT NULL COMMENT '安全库存',
  `virtual_status` tinyint(2) DEFAULT NULL COMMENT '虚拟库存启用状态  1 启用 0 禁用',
  `virtual_stock` int(11) DEFAULT NULL COMMENT '虚拟库存',
  `deleted` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否删除 1=已删除 0=未删除',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间,根据当前时间戳更新',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_stock_sid` (`sku_id`),
  KEY `idx_stock_pmid` (`merchant_id`,`product_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='库存表';

CREATE TABLE `sku_stock_log` (
  `id` bigint(16) NOT NULL AUTO_INCREMENT COMMENT '库存日志id',
  `sku_stock_id` int(11) NOT NULL COMMENT 'sku库存id',
  `sku_id` int(11) NOT NULL COMMENT 'skuId',
  `bf_total_stock` int(11) DEFAULT NULL COMMENT '变动前的总库存',
  `bf_stock` int(11) DEFAULT NULL COMMENT '变动前的可用库存',
  `bf_order_stock` int(11) DEFAULT NULL COMMENT '变动前的订单库存',
  `bf_safety_stock` int(11) DEFAULT NULL COMMENT '变动前的安全库存',
  `bf_virtual_stock` int(11) DEFAULT NULL COMMENT '变动前的虚拟库存',
  `af_total_stock` int(11) DEFAULT NULL COMMENT '变动后的总库存',
  `af_stock` int(11) DEFAULT NULL COMMENT '变动后的可用库存',
  `af_order_stock` int(11) DEFAULT NULL COMMENT '变动后的订单库存',
  `af_safety_stock` int(11) DEFAULT NULL COMMENT '变动后的安全库存',
  `af_virtual_stock` int(11) DEFAULT NULL COMMENT '变动后的虚拟库存',
  `description` varchar(255) DEFAULT NULL COMMENT '备注',
  `change_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '变动时间',
  `deleted` tinyint(2) DEFAULT NULL COMMENT '是否删除 1=已删除 0=未删除',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_sku_id` (`sku_id`) USING BTREE,
  KEY `idx_sku_stock_id` (`sku_stock_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='sku库存日志表';

CREATE TABLE `sku_stock_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `sku_stock_id` int(11) NOT NULL COMMENT '库存id',
  `order_no` varchar(50) NOT NULL COMMENT '订单编码',
  `order_item_no` varchar(50) NOT NULL COMMENT '订单明细编码',
  `status` tinyint(2) NOT NULL COMMENT '状态 1库存锁定，2库存释放，3库存扣除，4库存回加',
  `num` int(11) NOT NULL COMMENT '库存数量',
  `deleted` tinyint(2) DEFAULT '0' COMMENT '是否删除 1=已删除 0=未删除',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间,根据当前时间戳更新',
  PRIMARY KEY (`id`),
  KEY `idx_order_union` (`order_no`,`order_item_no`) USING BTREE,
  KEY `idx_sku_stock_id` (`sku_stock_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='库存订单操作记录表';
